import {ITEM_CHAINS,CHARACTERS,QUESTS,getLevel,getEra,getUnlockedChains,getQuestProgress,getPassProgress,getAlbumProgress} from './game.js';
import {ERAS,BUILDINGS,OFFERS,PASS_TIERS} from './travel-content.js';
import {tx,language,localized,chainName,itemName,animalName,nickname,bio,esc} from './i18n.js';
import {icon,itemArt,characterArt,uiSprite,eventArt,buildingArt} from './art-v4.js';
import {countdown} from './views-v4.js';

const reward=(type,count)=>`<span class="reward-token">${uiSprite(type)}<b>${count}</b></span>`;
const wide=(action,text,extra='')=>`<button class="wide-button green-button" data-action="${action}" ${extra}>${text}</button>`;
export function panelView(state,ui){
 const type=ui.panel,level=getLevel(state),unlocked=getUnlockedChains(state),travel=state.travel;
 if(type==='detail'){
  const item=ui.detail||{chain:'maedeup',level:0},chain=ITEM_CHAINS.find(c=>c.id===item.chain),available=unlocked.some(c=>c.id===chain.id),stage=item.level||0;
  const selected=state.board[ui.selected],canSell=selected&&!selected.generator&&!item.generator&&selected.chain===item.chain&&selected.level===stage;
  return {title:itemName(item),body:`<div class="detail-hero">${itemArt(item)}</div><div class="detail-level">${item.generator?uiSprite('energy'):`Lv. ${stage+1}`}</div>
   <div class="evolution-grid">${chain.items.map((entry,index)=>`<button class="evolution-step ${!item.generator&&index===stage?'current':''}" data-action="detail-step" data-chain="${chain.id}" data-level="${index}" aria-label="${itemName({chain:chain.id,level:index})}" title="${itemName({chain:chain.id,level:index})}">${itemArt({chain:chain.id,level:index})}<small>${index+1}</small>${index<5?icon('arrow'):icon('star')}</button>`).join('')}</div>
   <div class="merge-equation">${stage>0&&!item.generator?`${itemArt({chain:chain.id,level:stage-1})}<b>×2</b>${icon('arrow')}${itemArt(item)}`:`${itemArt({chain:chain.id,generator:true,level:0})}${uiSprite('energy')}<b>1</b>${icon('arrow')}${itemArt({chain:chain.id,level:0})}`}</div>
   ${canSell?`<button class="detail-sell" data-action="sell" aria-label="${tx('선택한 아이템 판매','Sell Selected Item')}">${icon('trash')}${tx('판매','Sell')} ${reward('coin',2**stage)}</button>`:''}
   ${available?`${!item.generator&&stage<5?`<button class="wide-button green-button" data-action="confirm-item" data-chain="${chain.id}" data-level="${stage}">${tx('상점에서 보기','View in Shop')} ${reward('gem',2**stage)}</button>`:''}<div class="detail-source"><h3>${tx('획득처','Source')}</h3><button data-action="source" data-chain="${chain.id}" aria-label="${tx('이 생성함으로 이동','Go to This Crate')}">${itemArt({chain:chain.id,generator:true,level:0})}${icon('arrow')}</button></div>`:`<div class="locked-notice">${icon('lock')} Lv.${chain.unlockLevel} · ${tx('시대가 열리면 만들 수 있어요','Available when this era opens')}</div>`}`};
 }
 if(type==='collection'){
  const chain=ITEM_CHAINS.find(c=>c.id===ui.collectionChain)||ITEM_CHAINS[0];
  return {title:tx('합성 도감','Merge Collection'),body:`<div class="collection-counter">${eventArt(3)}<strong>${state.discovered.length}<small> / 84</small></strong></div><div class="collection-icon-tabs">${ITEM_CHAINS.map(c=>`<button data-action="collection-tab" data-chain="${c.id}" aria-label="${chainName(c.id)}" title="${chainName(c.id)}" class="${c.id===chain.id?'active':''}">${itemArt({chain:c.id,level:5})}${level<(c.unlockLevel||1)?`<small>${icon('lock')}${c.unlockLevel}</small>`:''}</button>`).join('')}</div><h3 class="panel-subtitle">${chainName(chain.id)}</h3><div class="evolution-grid">${chain.items.map((item,index)=>`<button class="evolution-step ${state.discovered.includes(`${chain.id}:${index}`)?'discovered':''}" data-action="detail" data-chain="${chain.id}" data-level="${index}" aria-label="${itemName({chain:chain.id,level:index})}, ${tx('자세히 보기','Details')}">${itemArt({chain:chain.id,level:index})}<small>${index+1}</small>${icon('info')}</button>`).join('')}</div>`};
 }
 if(type==='workshop')return {title:tx('재료 생성함','Material Crates'),body:`<div class="workshop-status">${reward('energy',state.energy)}<span>${state.board.filter(x=>!x).length} ${tx('빈칸','free')}</span></div><div class="crate-grid">${ITEM_CHAINS.map(chain=>{const locked=level<(chain.unlockLevel||1);return `<div class="crate-card ${locked?'locked':''}"><button data-action="craft" data-chain="${chain.id}" aria-label="${itemName({chain:chain.id,generator:true,level:0})}" ${locked||state.energy===0||!state.board.includes(null)?'disabled':''}>${itemArt({chain:chain.id,generator:true,level:0})}<span class="crate-cost">${locked?`${icon('lock')} ${chain.unlockLevel}`:`${uiSprite('energy')}1`}</span></button><button class="crate-info" data-action="detail" data-chain="${chain.id}" data-level="0" data-generator="true" aria-label="${chainName(chain.id)}, ${tx('자세히 보기','Details')}">${icon('info')}</button></div>`;}).join('')}</div>`};
 if(type==='building'){
  const index=BUILDINGS.findIndex(b=>b.id===ui.building),b=BUILDINGS[index],built=travel.built.includes(b.id),available=level>=b.level;
  return {title:localized(b),body:`<div class="building-preview ${available?'':'preview-locked'}">${buildingArt(index)}</div><p class="era-caption">${localized(ERAS[b.era])} · Lv.${b.level}</p>${built?`<div class="built-stamp">${icon('check')} ${tx('여행의 추억이 완성됐어요','A new memory on your journey')}</div>`:available?`${wide('build',`${icon('hammer')}${reward('coin',b.cost)}`,`data-building="${b.id}" ${state.coins<b.cost?'disabled':''}`)}<p class="modal-footnote">${tx('완성 보상','Completion Reward')}: ${reward('gem',2)} +10 XP</p>${state.coins<b.cost?wide('board',tx('주문을 완성하고 엽전 모으기','Complete Orders to Earn Coins')):''}`:`<div class="locked-notice">${icon('lock')} Lv.${b.level}</div>${wide('board',tx('합성하고 다음 레벨로','Merge to Reach the Next Level'))}`}`};
 }
 if(type==='eras')return {title:tx('한국 시간 여행','A Journey Through Korea'),body:`<div class="era-list">${ERAS.map((era,index)=>`<button class="era-card ${level>=era.level?'unlocked':''} ${ui.eraView===index?'active':''}" data-action="visit-era" data-index="${index}"><span>${buildingArt(index*3+1)}</span><div><small>0${index+1} · Lv.${era.level}</small><strong>${localized(era)}</strong><p>${tx(era.subtitle,era.subtitleEn)}</p></div>${level>=era.level?icon('arrow'):icon('lock')}</button>`).join('')}</div>`};
 if(type==='characters'){
  const n=ui.character||0,c=CHARACTERS[n];return {title:tx('여행 친구들','Travel Friends'),body:`<div class="character-detail"><div class="character-hero">${characterArt(n)}</div><div><span class="character-tag">${tx(c.group,[0,2,3].includes(n)?'Village Friend':'Zodiac Friend')}</span><h3>${animalName(n)} <b>${nickname(n)}</b></h3><p>${bio(n)}</p><button class="favorite-recipe" data-action="favorite" data-chain="${c.favorite}">${chainName(c.favorite)} ${icon('arrow')}</button></div></div><div class="character-grid">${CHARACTERS.map((c,index)=>`<button class="character-card ${n===index?'active':''}" data-action="character" data-index="${index}" aria-label="${animalName(index)} ${nickname(index)}"><span class="character-card-art">${characterArt(index)}</span><strong>${animalName(index)}</strong></button>`).join('')}</div>`};
 }
 if(type==='inventory')return {title:tx('보관함','Storage'),body:`<div class="inventory-grid">${Array.from({length:8},(_,index)=>state.inventory[index]?`<button class="inventory-cell" data-action="retrieve" data-index="${index}" aria-label="${itemName(state.inventory[index])}, ${tx('꺼내기','Retrieve')}">${itemArt(state.inventory[index])}<small>${itemName(state.inventory[index])}</small></button>`:'<div class="inventory-cell vacant">+</div>').join('')}</div><p class="modal-footnote">${state.inventory.length} / 8 · ${tx('아이템을 눌러 보드로 꺼내세요','Tap an item to return it to the board')}</p>`};
 if(type==='daily')return {title:tx('오늘의 여행 선물','Today’s Travel Gift'),body:`<div class="event-hero">${eventArt(2)}</div><div class="reward-row">${reward('coin',50)}${reward('gem',2)}${reward('energy',10)}</div>${wide('claimDaily',travel.dailyClaimed?icon('check'):tx('선물 받기','Claim Gift'),travel.dailyClaimed?'disabled':'')}<p class="modal-footnote"><span data-countdown="day">${countdown('day')}</span> · ${tx('다음 선물까지','until the next gift')}</p>`};
 if(type==='memory'){
  const m=travel.memory;return {title:tx('짝꿍 카드','Memory Match'),body:`<div class="mini-status"><b>${m.matched.length/2} / 4</b><span>${m.moves} ${tx('번','moves')}</span></div>${m.cards.length?`<div class="memory-grid">${m.cards.map((avatar,index)=>{const flipped=m.flipped.includes(index)||m.matched.includes(index);return `<button class="memory-card ${flipped?'flipped':''} ${m.matched.includes(index)?'matched':''}" data-action="memoryFlip" data-index="${index}" aria-label="${tx('카드','Card')} ${index+1}, ${flipped?animalName(avatar):tx('뒤집기','Flip')}" ${m.matched.includes(index)||m.flipped.includes(index)?'disabled':''}>${flipped?characterArt(avatar):eventArt(0)}</button>`;}).join('')}</div>`:`<div class="event-hero">${eventArt(5)}</div>`}<div class="reward-row">${reward('coin',60)}<span class="xp-reward">+25 XP</span>${m.rewarded?icon('check'):''}</div>${!m.cards.length||m.completed?wide('memoryStart',m.completed?tx('다시 놀기','Play Again'):tx('시작','Play')):''}<p class="modal-footnote">${m.rewarded?tx('오늘의 보상 수령 완료 · 다시 놀 수 있어요','Today’s reward claimed · Replay for fun'):tx('같은 친구 두 장 찾기 · 하루 한 번 보상','Find four matching pairs · One reward per day')}</p>`};
 }
 if(type==='yut'){
  const y=travel.yut,positions=[[0,0],[0,1],[0,2],[0,3],[1,3],[2,3],[3,3],[3,2],[3,1],[3,0],[2,0],[1,0]],throws=['','도','개','걸','윷','모'],throwsEn=['','Do','Gae','Geol','Yut','Mo'];
  return {title:tx('윷 산책','Yut Walk'),body:`<div class="mini-status"><b>${y.position} / 12</b><span>${y.rolls} ${tx('번','throws')}</span></div><div class="yut-board">${positions.map(([r,c],index)=>`<span class="yut-space ${y.position%12===index?'current':''}" style="grid-row:${r+1};grid-column:${c+1}">${y.position%12===index?characterArt(7):index===0?icon('star'):'•'}</span>`).join('')}<div class="yut-center">${eventArt(4)}<b>${tx(throws[y.lastRoll],throwsEn[y.lastRoll])||'✦'}</b></div></div><div class="reward-row">${reward('coin',80)}<span class="xp-reward">+35 XP</span></div>${wide('rollYut',y.completed?icon('check'):tx('윷 던지기','Throw Yut'),y.completed?'disabled':'')}<p class="modal-footnote">${y.completed?tx('오늘의 산책 완료! 내일 또 만나요','Today’s walk is complete. See you tomorrow!'):tx('한 번에 1~5칸 · 12칸 완주하면 선물','Move 1–5 spaces · Complete 12 spaces for a gift')}</p>`};
 }
 if(type==='album')return {title:tx('한국 여행 앨범','Korea Travel Album'),body:`<div class="album-banner">${eventArt(3)}<div><strong>${travel.albumClaims.length} / ${ITEM_CHAINS.length}</strong><p>${tx('한 계열의 6종을 발견하면 기념품 완성','Discover all six items to complete a souvenir')}</p></div></div><div class="album-grid">${ITEM_CHAINS.map(chain=>{const p=getAlbumProgress(state,chain.id);return `<article class="album-card"><button data-action="collection-tab" data-chain="${chain.id}" aria-label="${chainName(chain.id)}">${itemArt({chain:chain.id,level:5})}<strong>${chainName(chain.id)}</strong></button><button class="album-claim ${p.ready?'green-button':''}" data-action="claimAlbum" data-chain="${chain.id}" ${p.ready?'':'disabled'}>${p.claimed?icon('check'):p.ready?reward('gem',3):`${p.have} / 6`}</button></article>`;}).join('')}</div>`};
 if(type==='pass')return {title:tx('일주일 한국 여행','Weekly Korea Journey'),body:`<div class="pass-banner">${eventArt(1)}<div><strong>${travel.pass.orders} ${tx('개의 소원',travel.pass.orders===1?'wish fulfilled':'wishes fulfilled')}</strong><p data-countdown="week">${countdown('week')}</p></div></div><div class="pass-head"><span>${tx('주문','Orders')}</span><span>${tx('여행 보상','Travel Rewards')}</span><span>${tx('프리미엄','Premium')}</span></div><div class="pass-tiers">${PASS_TIERS.map((tier,index)=>{const free=getPassProgress(state,index,false),premium=getPassProgress(state,index,true);return `<div class="pass-tier"><b>${tier.target}</b><button class="pass-claim ${free.ready?'green-button':''}" data-action="claimPass" data-tier="${index}" data-premium="false" ${free.ready?'':'disabled'}>${free.claimed?icon('check'):`${reward('coin',tier.coins)}${reward('gem',tier.gems)}`}</button><button class="pass-claim premium ${premium.ready?'green-button':''}" data-action="claimPass" data-tier="${index}" data-premium="true" ${premium.ready?'':'disabled'}>${premium.claimed?icon('check'):`${reward('gem',tier.premiumGems)}${premium.locked?icon('lock'):''}`}</button></div>`;}).join('')}</div>${travel.pass.premium?`<div class="built-stamp">${icon('check')} ${tx('프리미엄 여행 중','Premium Journey Active')}</div>`:wide('confirm-pass',`${tx('프리미엄 열기','Unlock Premium')}${reward('gem',20)}`)}<p class="modal-footnote">${tx('주문을 완성해 무료·프리미엄 보상을 모아요','Complete orders to earn free and premium rewards')}</p>`};
 if(type==='shop'||type==='welcome'){
  if(ui.purchase){const p=ui.purchase,offer=p.type==='offer'?OFFERS.find(o=>o.id===p.id):null,cost=offer?.cost??(p.type==='pass'?20:2**p.level),art=offer?eventArt(offer.art):p.type==='pass'?eventArt(1):itemArt({chain:p.chain,level:p.level});return {title:tx('여행 상점','Travel Shop'),body:`<div class="event-hero">${art}</div><h3 class="panel-subtitle">${offer?localized(offer):p.type==='pass'?tx('프리미엄 여행 패스','Premium Journey Pass'):itemName(p)}</h3>${offer?`<div class="reward-row">${offer.coins?reward('coin',offer.coins):''}${reward('energy',offer.energy)}</div>`:''}${wide('purchase',`${tx('교환','Exchange')}${reward('gem',cost)}`,state.gems<cost?'disabled':'')}<p class="modal-footnote">${tx('게임 보석으로 교환 · 실제 결제 없음','Exchange in-game gems · No real payment')}</p>${offer?`<p class="modal-footnote">${tx(`에너지 ${offer.energy}칸의 여유가 필요해요`,`Requires room for ${offer.energy} energy`)}</p>`:''}`};}
  return {title:tx('여행 상점','Travel Shop'),body:`<div class="shop-balance">${reward('gem',state.gems)}</div><div class="offer-list">${OFFERS.map(offer=>{const bought=offer.limit==='once'?Boolean(travel.offers[offer.id]):travel.offers[offer.id]===travel.day;return `<button class="offer-card" data-action="offer" data-offer="${offer.id}" ${bought?'disabled':''}><span>${eventArt(offer.art)}</span><div><strong>${localized(offer)}</strong><div class="offer-rewards">${offer.coins?reward('coin',offer.coins):''}${reward('energy',offer.energy)}</div></div><b>${bought?icon('check'):reward('gem',offer.cost)}</b></button>`;}).join('')}</div>${wide('pass',`${eventArt(1)}${tx('여행 패스','Journey Pass')}${icon('arrow')}`)}<p class="modal-footnote">${tx('게임 보석으로 교환 · 실제 결제 없음','Exchange in-game gems · No real payment')}</p>`};
 }
 if(type==='energy')return {title:tx('에너지 충전','Recharge Energy'),body:`<div class="energy-display">${uiSprite('energy')}<strong>${state.energy}<small> / 100</small></strong></div><div class="shop-options"><button class="shop-option" data-action="refill" ${state.coins<50||state.energy>=100?'disabled':''}><span>${reward('energy',30)}</span><strong class="green-button">${reward('coin',50)}</strong></button><button class="shop-option" data-action="gemRefill" ${state.gems<5||state.energy>=100?'disabled':''}><span>${reward('energy',50)}</span><strong class="pink-button">${reward('gem',5)}</strong></button></div><p class="modal-footnote">${tx('1분마다 +1 · 최대 100','+1 every minute · Maximum 100')}</p>${wide('shop',tx('여행 꾸러미 보기','View Travel Bundles'))}`};
 if(type==='quests')return {title:tx('친구들의 소원','Friends’ Wishes'),body:`<div class="quest-list">${QUESTS.map((q,index)=>{const p=getQuestProgress(state,q),titles=['Merge Master','Friendly Traveler','Beautiful Hanbok'],descriptions=['Merge 10 items','Complete 5 orders','Discover 4 hanbok items'];return `<article class="quest-card"><div class="quest-image">${index===2?itemArt({chain:'hanbok',level:5}):uiSprite('medal')}</div><div class="quest-copy"><h3>${tx(q.title,titles[index])}</h3><p>${tx(q.description,descriptions[index])}</p><div class="progress-track"><span style="width:${Math.min(p.have/p.total*100,100)}%"></span><b>${p.have}/${p.total}</b></div></div><button class="quest-claim ${p.ready?'green-button':''}" data-action="claimQuest" data-quest="${q.id}" ${p.ready?'':'disabled'}>${p.claimed?icon('check'):reward(q.reward.gems?'gem':'coin',q.reward.gems||q.reward.coins)}</button></article>`;}).join('')}</div>`};
 if(type==='settings')return {title:tx('설정','Settings'),body:`<div class="settings-row"><strong>${tx('언어','Language')}</strong><button class="setting-choice" data-action="language">${language()==='ko'?'한국어 → English':'English → 한국어'}</button></div><div class="settings-row"><strong>${tx('효과음','Sound')}</strong><button class="sound-switch ${ui.sound?'on':''}" data-action="sound" role="switch" aria-checked="${ui.sound}"><span></span></button></div><div class="settings-row"><strong>${tx('여행 레벨','Travel Level')}</strong><b>Lv.${level}</b></div>${wide('help',tx('플레이 방법','How to Play'))}<p class="modal-footnote">${tx('이 기기에 자동 저장됩니다','Your progress is saved on this device')}</p>`};
 if(type==='help')return {title:tx('폴 인 코리아','Fall in Korea'),body:`<div class="help-demo">${itemArt({chain:'maedeup',level:0})}<b>×2</b>${icon('arrow')}${itemArt({chain:'maedeup',level:1})}</div><ol class="help-steps"><li><b>1</b><div><strong>${tx('재료 생성함을 톡','Tap a Material Crate')}</strong><p>${tx('번개가 있는 생성함에서 에너지 1로 재료를 꺼내요.','Tap a crate with a lightning bolt to create an item for 1 energy.')}</p></div></li><li><b>2</b><div><strong>${tx('같은 아이템을 합쳐요','Merge Matching Items')}</strong><p>${tx('드래그하거나 차례로 눌러 합쳐요. ⓘ에서 전체 합성 경로를 볼 수 있어요.','Drag identical items together or tap them in turn. Use ⓘ to see the full merge path.')}</p></div></li><li><b>3</b><div><strong>${tx('주문을 완성하고 한국을 여행해요','Complete Orders & Explore Korea')}</strong><p>${tx('주문으로 레벨을 올리고, 홈 맵에서 건물을 지어요. Lv.4·7·10에 새로운 시대와 물건이 열려요.','Level up through orders and build on the home map. New eras and items unlock at levels 4, 7 and 10.')}</p></div></li></ol>${wide('board',tx('여행 시작','Start Your Journey'))}`};
 return {title:'Fall in Korea',body:''};
}
