import {getLevel,getEra,getUnlockedChains,getQuestProgress,getPassProgress,getOrderProgress,canFulfillOrder,ITEM_CHAINS,COLS,QUESTS} from './game.js';
import {ERAS,BUILDINGS,PASS_TIERS} from './travel-content.js';
import {tx,language,localized,itemName,animalName,esc} from './i18n.js';
import {icon,itemArt,characterArt,uiSprite,eventArt,buildingArt} from './art-v4.js';

export function countdown(kind,now=Date.now()){
 const date=new Date(now),end=new Date(Date.UTC(date.getUTCFullYear(),date.getUTCMonth(),date.getUTCDate()+1));
 if(kind==='week')end.setUTCDate(end.getUTCDate()+(7-end.getUTCDay()+1)%7);
 const seconds=Math.max(0,Math.floor((end.getTime()-now)/1000)),days=Math.floor(seconds/86400),hours=Math.floor(seconds/3600)%24,minutes=Math.floor(seconds/60)%60;
 return days?`${days}d ${hours}h`:`${hours}h ${String(minutes).padStart(2,'0')}m`;
}
export function header(state){return `<header class="game-top"><button class="travel-wordmark" data-action="home" aria-label="Fall in Korea"><span>FALL IN <b>KOREA</b></span><small>${tx('폴 인 코리아','MERGE · BUILD · TRAVEL')}</small></button><div class="top-actions"><button class="language-button" data-action="language" aria-label="${tx('Switch to English','한국어로 변경')}">${language()==='ko'?'EN':'한국어'}</button><button class="round-button" data-action="settings" aria-label="${tx('설정','Settings')}">${icon('settings')}</button><button class="round-button shop-orb" data-action="shop" aria-label="${tx('여행 상점','Travel Shop')}">${eventArt(7)}</button></div></header>
 <section class="game-hud" aria-label="${tx('게임 재화','Resources')}"><button class="profile-frame" data-action="characters" aria-label="${tx('마을 친구','Travel Friends')}">${characterArt(0)}<span class="level-star">${icon('star')}<b>${getLevel(state)}</b></span></button><button class="resource energy-resource" data-action="energy" aria-label="${tx('에너지 충전','Recharge Energy')}">${uiSprite('energy')}<strong id="energy-value">${state.energy}</strong><span class="green-plus">+</span><small id="energy-timer">${state.energy===100?'MAX':energyTime(state)}</small></button><button class="resource coins-resource" data-action="quests" aria-label="${tx('엽전과 미션','Coins & Missions')}">${uiSprite('coin')}<strong id="coin-value">${state.coins.toLocaleString()}</strong></button><button class="resource gems-resource" data-action="shop" aria-label="${tx('보석 상점','Gem Shop')}">${uiSprite('gem')}<strong id="gem-value">${state.gems}</strong><span class="green-plus">+</span></button></section>`;}
export function energyTime(state){const seconds=Math.ceil(Math.max(0,60_000-(Date.now()-state.lastEnergyAt))/1000);return `${Math.floor(seconds/60)}:${String(seconds%60).padStart(2,'0')}`;}
function eventButton(action,art,ribbon,extra='',badge=''){return `<button class="travel-event ${extra}" data-action="${action}" aria-label="${({daily:tx('매일 여행 선물','Daily Gift'),memory:tx('짝꿍 카드','Memory Match'),album:tx('여행 앨범','Travel Album'),yut:tx('윷 산책','Yut Walk'),pass:tx('여행 패스','Journey Pass'),welcome:tx('첫 여행 꾸러미','First Journey Bundle')})[action]}"><span class="travel-event-art">${eventArt(art)}</span><span class="travel-event-ribbon">${ribbon}</span>${badge?`<b class="event-dot">${badge}</b>`:''}</button>`;}
export function homeView(state,ui){
 const era=ERAS[ui.eraView],actualEra=getEra(state),level=getLevel(state);
 const hasPassReward=PASS_TIERS.some((_,index)=>getPassProgress(state,index,false).ready||getPassProgress(state,index,true).ready);
 return `<div class="stage-slot"><main class="game-shell home-screen" aria-label="${tx('한국 여행 맵','Korea Travel Map')}"><div class="map-viewport" tabindex="0" aria-label="${tx('상하좌우로 끌어서 한국을 여행해 보세요','Drag in any direction to explore Korea')}"><div class="travel-world">${BUILDINGS.map((b,index)=>{
  const built=state.travel.built.includes(b.id),available=level>=b.level;
  return `<button class="map-node ${built?'built':available?'available':'locked'}" data-action="building" data-building="${b.id}" style="left:${b.x+135}px;top:${b.y*1800/1300+150}px;--era-color:${ERAS[b.era].color}" aria-label="${localized(b)}, ${built?tx('완성','Built'):available?tx('건설 가능','Ready to Build'):`Lv.${b.level}`}" title="${localized(b)}">${built?buildingArt(index):available?`<span class="building-foundation">${icon('hammer')}</span>`:'<span class="map-mist" aria-hidden="true"></span>'}<span class="node-label">${built?icon('check'):available?`${uiSprite('coin')}${b.cost}`:`${icon('lock')} ${b.level}`}</span>${built&&b.level===Math.min(level,12)?`<span class="map-friend">${characterArt((index+1)%15)}</span>`:''}</button>`;
 }).join('')}<span class="map-sea-glint"></span></div></div>${header(state)}
 <button class="era-ribbon" data-action="eras" aria-label="${tx('시대별 여행','Travel Through Time')}"><span>${ui.eraView>ERAS.indexOf(actualEra)?icon('lock'):icon('globe')}</span><strong>${localized(era)}</strong><b>Lv.${era.level}${icon('arrow')}</b></button>
 <div class="event-rail left-rail">${eventButton('daily',2,state.travel.dailyClaimed?icon('check'):`<span data-countdown="day">${countdown('day')}</span>`,'mint',state.travel.dailyClaimed?'':'!')}${eventButton('memory',5,state.travel.memory.rewarded?icon('check'):`${state.travel.memory.matched.length/2} / 4`,'purple')}${eventButton('album',3,`${state.discovered.length} / 84`,'pink')}</div>
 <div class="event-rail right-rail">${eventButton('welcome',2,state.travel.offers.welcome?icon('check'):`${uiSprite('gem')}5`,'gold')}${eventButton('yut',4,state.travel.yut.completed?icon('check'):`${state.travel.yut.position} / 12`,'mint')}${eventButton('pass',1,`<span data-countdown="week">${countdown('week')}</span>`,'purple',hasPassReward?'!':'')}</div>
 <nav class="home-nav" aria-label="${tx('메뉴','Menu')}"><button class="nav-orb" data-action="inventory" aria-label="${tx('보관함','Storage')}">${uiSprite('bag')}</button><button class="nav-orb" data-action="album" aria-label="${tx('여행 앨범','Travel Album')}">${eventArt(3)}</button><button class="nav-orb" data-action="pass" aria-label="${tx('여행 패스','Journey Pass')}">${eventArt(0)}</button><button class="play-travel" data-action="board" aria-label="${tx('합성 게임 시작','Play Merge Game')}">${icon('play')}${uiSprite('energy')}</button></nav>
 <div class="home-xp" aria-label="${tx('레벨 진행','Level Progress')}"><span style="width:${state.xp%100}%"></span><b>${state.xp%100} / 100</b></div></main></div>`;
}
export function boardView(state,ui){return `<div class="stage-slot"><main class="game-shell board-screen era-${getEra(state).id}" aria-label="${tx('합성 게임','Merge Game')}"><div class="scene-background" aria-hidden="true"></div><div class="scene-vignette" aria-hidden="true"></div>${header(state)}
 <div class="board-events"><button class="mini-event" data-action="quests" aria-label="${tx('미션','Missions')}">${uiSprite('medal')}<small>${Math.min(state.mergeCount,10)}/10</small></button><button class="board-era" data-action="home">${uiSprite('map')}<span>${localized(getEra(state))}</span>${icon('arrow')}</button><button class="mini-event" data-action="collection" aria-label="${tx('전체 합성 도감','Merge Collection')}">${eventArt(3)}<small>${state.discovered.length}/84</small></button></div>
 <section class="orders-area" aria-label="${tx('손님 주문','Customer Orders')}"><div class="order-track">${state.orders.map((order,index)=>orderCard(state,order,index)).join('')}</div></section>
 <section class="board-area" aria-label="${tx('합성 테이블','Merge Table')}"><div class="board-edge"><div class="merge-board" role="group" aria-label="${tx('7열 9행 머지 보드','7 by 9 Merge Board')}">${state.board.map((item,index)=>cell(item,index,ui.selected)).join('')}</div></div></section>
 <footer class="game-toolbar"><button class="nav-orb" data-action="inventory" aria-label="${tx('보관함','Storage')}">${uiSprite('bag')}${state.inventory.length?`<b class="orb-count">${state.inventory.length}</b>`:''}</button><div class="selection-panel" id="selection-info">${selectionView(state,ui)}</div><button class="nav-orb" data-action="home" aria-label="${tx('여행 맵','Travel Map')}">${uiSprite('map')}</button></footer></main></div>`;}
function orderCard(state,order,index){const ready=canFulfillOrder(state,order),p=getOrderProgress(state,order);return `<article class="order-card card-${index} ${ready?'ready':''}"><button class="customer-portrait" data-action="character" data-index="${order.avatar}" aria-label="${animalName(order.avatar)}">${characterArt(order.avatar)}</button><div class="order-required">${order.requirements.map(req=>{const have=state.board.filter(item=>item&&!item.generator&&item.chain===req.chain&&item.level===req.level).length;return `<button class="required-item ${have>=req.quantity?'complete':''}" data-action="detail" data-chain="${req.chain}" data-level="${req.level}" aria-label="${itemName(req)} ${req.quantity}, ${tx('자세히 보기','Details')}">${itemArt(req)}<span class="requirement-count">${have>=req.quantity?icon('check'):`${Math.min(have,req.quantity)}/${req.quantity}`}</span></button>`;}).join('')}<span class="order-reward">${uiSprite('coin')}<b>+${order.coins}</b></span></div><button class="order-submit ${ready?'green-button':''}" data-action="fulfill" data-order="${esc(order.id)}" aria-label="${animalName(order.avatar)} ${tx('주문 전달','Deliver Order')}" ${ready?'':'disabled'}>${ready?icon('check'):`${p.have} / ${p.total}`}</button></article>`;}
function cell(item,index,selected){return `<button class="board-cell ${(Math.floor(index/COLS)+index%COLS)%2?'tile-light':'tile-dark'} ${item?'occupied':'empty'} ${item?.generator?'is-generator':''} ${selected===index?'selected':''}" data-cell="${index}" aria-label="${index+1}, ${item?itemName(item):tx('빈 칸','Empty Cell')}" aria-pressed="${selected===index}" title="${item?itemName(item):''}">${itemArt(item)}${item?.generator?`<span class="generator-bolt">${uiSprite('energy')}</span>`:item&&item.level>=3?`<span class="level-pips">${Array.from({length:item.level-2},()=>'<i></i>').join('')}</span>`:''}</button>`;}
export function selectionView(state,ui){const item=state.board[ui.selected];if(!item)return `<button class="selection-guide" data-action="help" aria-label="${tx('플레이 방법','How to Play')}">${itemArt({chain:'maedeup',level:0})}<b>+</b>${itemArt({chain:'maedeup',level:0})}${icon('arrow')}${itemArt({chain:'maedeup',level:1})}</button><button class="detail-icon" data-action="workshop" aria-label="${tx('생성함 보기','Material Crates')}">${icon('hammer')}</button>`;return `<span class="selected-item-art">${itemArt(item)}</span><div class="selected-item-copy"><strong>${item.generator?'':esc(itemName(item))}</strong><span class="selection-level">${item.generator?`${uiSprite('energy')}1`:`Lv.${item.level+1}`}</span></div><button class="detail-icon" data-action="selected-detail" aria-label="${tx('자세히 보기','Details')}">${icon('info')}</button>${item.generator?`<button class="small-action green-button" data-action="generate" data-index="${ui.selected}" aria-label="${tx('재료 생성','Generate Material')}">${uiSprite('energy')}</button>`:`<button class="small-action store-button" data-action="store" aria-label="${tx('선택한 아이템 보관','Store Selected Item')}">${uiSprite('bag')}</button>`}`;}
